<HomeScreen>:
    Label:
        font_size: 70
        center_x: root.width/2
        top: root.top - 50
        text: "Title"
    Label:
        font_size: 50
        center_x: root.width/2
        top: root.top - 150
        text: "Details"
    Button:
        size_hint: None, None
        size: 120,40
        center_x: root.width/2
        top: root.top - 300
        size_hint: .1, .1
        text: "start"